### ISSUE TITLE
FormNotFoundError: no form matching name 'simTradePreview'

### ISSUE THREAD

**Issue by JoePython1** [kirkthaker/investopedia-trading-api#6]
Getting form error now.
         >> client.trade("SPY", Action.short, 20)
Tried changing simTradePreview to simTrade and didnt work either.

**Comment by kirkthaker** [comment]
I can't replicate the issue on my end - the short order goes through successfully, which means that the form names are fine. 

If mechanize cannot find the form when you run the code, it means that something goes wrong when you submit the trade order and you're never taken to the final submission page. Could you describe your Investopedia setup in more detail - what investing game you're part of, etc?

**Comment by JoePython1** [comment]
I created the account yesterday.


![firefox_screenshot_2016-01-14t13-15-23 446z](https://cloud.githubusercontent.com/assets/307737/12325283/197ead36-ba97-11e5-8066-5540034c6c1d.png)

And the screen for trading.
![investopedia stock simulator - trade a stock 2016-01-14 08-22-28](https://cloud.githubusercontent.com/assets/307737/12325405/04c6f352-ba98-11e5-9cdf-2b2b7d21f703.png)

**Comment by kirkthaker** [comment]
I think I figured out your error! It's not because of the API, it's an issue with your trade itself. When I tried to submit the order manually, in the Beginner game, I got the following message: "This order was not executed because it violated the game's diversification rule. The diversification rule refers to an in-game setting that prevents users from spending more than 25.00 % of their total funds in a single trade. The purpose of this rule is to make the experience more realistic. In real life, very few investors would be willing to risk their entire investment funds on just one or two positions. " 

Buying 20 shares of SPY would be roughly 38% of your $10,000 portfolio at market price. Try changing the amounts or shares to fit the diversification rule, and the order should go through.

**Comment by JoePython1** [comment]
I tried buying cheap stock USO - $9. Still no cigar. Wonder whether i could introspect the html?

````python
In [3]: client.trade("USO", Action.buy, 5)
---------------------------------------------------------------------------
FormNotFoundError                         Traceback (most recent call last)
<ipython-input-3-9b7f93ad469f> in <module>()
----> 1 client.trade("USO", Action.buy, 5)

/home/jopython/Downloads/investopedia-trading-api/investopedia.py in trade(self, symbol, orderType, quantity, priceType, price, duration)
     92         self.fetch('/simulator/trade/tradestock.aspx')
     93         handle = self.br
---> 94         handle.select_form(name="simTradePreview")
     95 
     96         # input order type, quantity, etc.

/home/jopython/anaconda2/lib/python2.7/site-packages/mechanize/_mechanize.pyc in select_form(self, name, predicate, nr)
    522             if orig_nr is not None: description.append("nr %d" % orig_nr)
    523             description = ", ".join(description)
--> 524             raise FormNotFoundError("no form matching "+description)
    525 
    526     def click(self, *args, **kwds):

```FormNotFoundError: no form matching name 'simTradePreview'

**Comment by kirkthaker** [comment]
The form definitely exists - here's a screenshot of the HTML, with the form tag highlighted in blue. 
Perhaps the issue is with your local Python setup? (version, etc.)
<img width="972" alt="screen shot 2016-01-14 at 10 07 22 pm" src="https://cloud.githubusercontent.com/assets/6157162/12344468/659ed79e-bb0b-11e5-80c1-e5ff84e935a9.png">
